### PR TITLE
Add TabUltraCPro

### PR DESCRIPTION
**Pull request by RenateUSB**

### CODE REVIEW

**Comment by RenateUSB** [comment]
@Hagb bump?

**Review by Hagb — APPROVED** [review]
Sorry for my delay. LGTM!

**Comment by sellin82** [comment]
https://github.com/Hagb/decryptBooxUpdateUpx/issues/84

**Comment by sellin82** [comment]
ONYX BOOX Note Air 3 BooxKeys.csv BooxKeys Please upload and update the key

**Pull request merged**
