### PR TITLE
Add string for Leaf3

### PR DESCRIPTION
**Pull request by AndyCGYan**
https://github.com/Hagb/decryptBooxUpdateUpx/issues/64

### CODE REVIEW

**Comment by AndyCGYan** [comment]
Verified by decrypting first OTA of this model.

**Comment by happyjake** [comment]
Works on my Leaf3

**Comment by Hagb** [comment]
Merged. Thanks!

**Comment by ruanimal** [comment]
@AndyCGYan  which GSI image should working? I have try some images, but screen is blank after reboot.

images
- lineage-18.1-20240121-UNOFFICIAL-arm64_bvS.img.xz
- lineage-19.1-20240419-UNOFFICIAL-arm64_bvS.img.xz

**Comment by AndyCGYan** [comment]
> @AndyCGYan which GSI image should working? I have try some images, but screen is blank after reboot.

I don't try to have every device I get run GSI. I reckon it'd be time-consuming to get e-ink-specific controls fully working on AOSP, so I just leave it rooted stock.

That said, the GSIs do boot - connect it to scrcpy, it displays content just fine. Therefore, GSIs are good for extracting partitions from the device, incl. those not covered by FOTAs.

**Comment by ArthurZhou** [comment]
here it is, the leaf3 package
url: `http://data.onyx-international.cn/api/firmware/update?where={%22buildNumber%22:0,%22buildType%22:%22user%22,%22deviceMAC%22:%22%22,%22lang%22:%22zh_CN%22,%22model%22:%22Leaf3%22,%22submodel%22:%22%22,%22fingerprint%22:%22%22}`

content: 
```json
{"_id":"66e3f638d3a944141101f090","updatedAt":"2024-09-20T02:01:52.988Z","createdAt":"2024-09-13T08:22:16.960Z","md5":"8ed6ad7599ed5b21d774c3dbb2262364","model":"Leaf3","submodel":"","brand":"ONYX","fingerprint":"Onyx/Leaf3/Leaf3:11/2024-09-11_04-50_3.5.4_fbdec6b69a/47380:user/release-keys","buildType":"user","buildNumber":47380,"buildDisplayId":"2024-09-11_04-50_3.5.4_fbdec6b69a","excludeGroups":false,"parentFingerprint":"","force":false,"__v":0,"availableCount":0,"whitelistMAC":["00:0a:00:16:f9:e3"],"size":1735231521,"betaGroups":[],"downloadUrlList":["http://firmware.boox.com/8ed6ad7599ed5b21d774c3dbb2262364/update.upx"],"changeList":["平板","BOOX OS 3.5.4（正式版）","全新升级，效率加倍！非常期待您的体验与反馈！","【请您注意】","-更新将分批次推送，若您检测不到更新，请您第二天再尝试； ","-更新前请务必备份好您的重要数据（笔记、资料），避免异常情况导致数据丢失；","-升级后系统会进行优化调整，初期可能会增加耗电，使用一段时间后续航会恢复稳定；","-升级后不支持系统降级，请在升级前仔细考虑。","系统更新内容如下","*******************************************","系统：","1. 新增 快捷手写笔记入口（控制中心-快捷手写笔记tile，悬浮球、底部手势自定义、侧边手势自定义）；","2. 新版本侧边手势默认配置为【向右滑动“返回”】，【向左滑动创建“快捷笔记”】。可在【侧边手势】中进行修改；","3. 修复升级后，第三方APP需要重置优化配置才能显示正常的问题；","4. 修复系统方向旋转不生效的问题；","5. 修复WIFI连接相关的问题；","6. 优化部分UI界面；","7. 修复部分小语种键盘重音显示不全的问题；","阅读：","1. 调整双开-AI阅读助手为 调用系统 AI助手 悬浮窗，支持6寸和7寸单触型号；","2. 调整双触型号的手触开关到顶部工具栏，方便快速切换；","3. PDF增加离线OCR，支持37个语种（识别率略比在线版低一些）；","4. 悬浮菜单增加背景色切换键，方便快速切换黑底白字显示；","5. 双开翻译，增加一键复制全部；","6. 修复漫画、论文等模式下，手写和高亮位置不对的问题；","笔记：","1. 新增会议笔记，支持录音、语音转文本和手写功能;","2. 手写笔记-插入录音，调整到一级工具栏，方便快速调用；","3. 手写笔记-插入录音，增加保留后台录音的开关；","4. 优化笔记内搜索栏-搜索结果列表页效果；","5. 优化笔记缩略图界面文字显示；","6. 支持笔记批量同步到第三方网盘或笔记账号；","7. 笔记划屏翻页距离调整，避免误翻页"],"fwType":"release"}
```

**Pull request merged**
