### PR TITLE
Onyx Leaf 2 strings

### PR DESCRIPTION
**Pull request by CrazyCoder**
Strings from the Onyx Leaf 2 device

### CODE REVIEW

**Comment by CrazyCoder** [comment]
Sorry for the duplicate (https://github.com/Hagb/decryptBooxUpdateUpx/pull/46).

**Comment by FreeTheTech101** [comment]
Tried the keys from #46 on the [latest firmware available](http://firmware-us-volc.boox.com/a29114b257c8a08ecc6e486726ac3fdf/update.upx) for the Leaf 2, and it did not work. However, this set did. Based on that, you might want to re-open this PR.

**Comment by Hagb** [comment]
@CrazyCoder  Thanks for your strings!

> Tried the keys from #46 on the [latest firmware available](http://firmware-us-volc.boox.com/a29114b257c8a08ecc6e486726ac3fdf/update.upx) for the Leaf 2, and it did not work. However, this set did. Based on that, you might want to re-open this PR.

@FreeTheTech101 It seems that there are two models called "Leaf 2". The one in #46 has `"MODEL": "Leaf2_P"`, and the one in this PR has `"MODEL": "Leaf2"`.

**Comment by sargunv** [comment]
Can confirm these are what I got on my Leaf 2

Screenshot_20230123-220224

**Comment by Hagb** [comment]
`Leaf2_P` is likely the China Mainland variant. (https://github.com/Hagb/decryptBooxUpdateUpx/pull/46#issuecomment-1403700386)

**Comment by Hagb** [comment]
Thanks for your contribution! The PR is merged now.

**Pull request merged**
